FROM golang:1.22-alpine

WORKDIR /app

# Install the correct legacy path for older air versions
RUN go install github.com/cosmtrek/air@v1.52.1

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the rest of the source code
COPY . .

# Expose the API port
EXPOSE 8080

# Run air with the config file
CMD ["air", "-c", ".air.toml"]
