// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Returns a welcome message",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["root"],
                "summary": "Root endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {"type": "string"}
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the health status of the service",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["health"],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"$ref": "#/definitions/model.HealthResponse"}
                    }
                }
            }
        },
        "/info": {
            "get": {
                "description": "Returns information about the service",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["info"],
                "summary": "Get service information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"$ref": "#/definitions/model.ServiceInfo"}
                    }
                }
            }
        }
    },
    "definitions": {
        "model.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {"type": "string", "example": "ok"},
                "timestamp": {"type": "string", "example": "2024-01-01T00:00:00Z"},
                "version": {"type": "string", "example": "1.0.0"}
            }
        },
        "model.ServiceInfo": {
            "type": "object",
            "properties": {
                "name": {"type": "string", "example": "monitor-service"},
                "version": {"type": "string", "example": "1.0.0"},
                "description": {"type": "string", "example": "Monitoring service for digi-pulse"},
                "environment": {"type": "string", "example": "production"}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Monitor Service API",
	Description:      "Monitoring service for digi-pulse",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}